Added functions to add Arctic Report Card annotations into data packages
NCEAS/arcticdatautils pull request #203
Opened 2024-07-03 19:46 UTC by justinkadi

- Added 2 functions into `ontology.R` for creating new annotations for the Arctic Report Card datasets

`eml_arcrc_key_variable_annotation(valueLabel)`, `eml_arcrc_essay_annotation(valueLabel)`

property: "isAbout", value: "key variable" (e.g. "isAbout" "sea surface temperature")
property: "influenced", value: "essay topic" (e.g. "influenced" "Greenland Ice Sheet Indicator")

- Added 1 function into `eml.R` for actually adding the new annotation into the EML doc

`eml_arcrc_add_annotation(doc, property, label)`
`eml_arcrc_add_annotation(doc, "isAbout", "sea surface temperature")`
`eml_arcrc_add_annotation(doc, "isAbout", c("sea ice", "sea surface temperature"))`
`eml_arcrc_add_annotation(doc, "influenced", "Greenland Ice Sheet Indicator")`

- Added test files and documentation into `test_ontology.R` and `test_eml.R`

2024-07-03 19:54 UTC, jeanetteclark requested changes
the code looks good. could you have a look at the check results here: https://github.com/NCEAS/arcticdatautils/actions/runs/9783945702/job/27013717921?pr=203 we should get those tests passing again (even though they are not from your changes), and try to resolve the notes as well. I think the note regarding exported objects (`:::`) can be ignored, but we should try to fix the global variable ones. IIRC I think that those result from issues with dplyr syntax

2024-07-03 22:51 UTC, mbjones commented
> I think the note regarding exported objects (`:::`) can be ignored

There is almost never a good reason to use `:::`, and it will never pass muster in an externally published package on CRAN. Why do you need it here? If the method you need is not exported, then that should be changed, rather than going around it. By not exporting a method, the package author is explicitly saying "never use this method, it is private to the package". Failing to heed that will lead to broken code eventually. See: https://stat.ethz.ch/R-manual/R-devel/library/base/html/ns-dblcolon.html

2024-07-03 22:59 UTC, jeanetteclark commented
not sure why the `:::` got put there in the first place - they are calls to methods from the `dataone` package, I think put in when Bryce first wrote the package

2024-07-08 20:24 UTC, jeanetteclark approved these changes

2024-07-09 17:44 UTC, merged